CREATE TABLE instruments (
  symbol TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  indices TEXT[] NOT NULL DEFAULT '{}',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_instruments_name_lower ON instruments (LOWER(name));
CREATE INDEX idx_instruments_indices ON instruments USING GIN (indices);

ALTER TABLE instruments ENABLE ROW LEVEL SECURITY;

-- Public reference data: any signed-in user can read; nobody can write
-- (we seed via migrations / privileged jobs only).
CREATE POLICY "instruments_read_all"
  ON instruments FOR SELECT
  TO authenticated, anon
  USING (true);

-- Seed: S&P 500 + Nasdaq-100 (sourced from Wikipedia / datasets/s-and-p-500-companies)
INSERT INTO instruments (symbol, name, indices) VALUES
  ('A', 'Agilent Technologies', ARRAY['SPX']::text[]),
  ('AAPL', 'Apple Inc.', ARRAY['NDX','SPX']::text[]),
  ('ABBV', 'AbbVie', ARRAY['SPX']::text[]),
  ('ABNB', 'Airbnb', ARRAY['NDX','SPX']::text[]),
  ('ABT', 'Abbott Laboratories', ARRAY['SPX']::text[]),
  ('ACGL', 'Arch Capital Group', ARRAY['SPX']::text[]),
  ('ACN', 'Accenture', ARRAY['SPX']::text[]),
  ('ADBE', 'Adobe Inc.', ARRAY['NDX','SPX']::text[]),
  ('ADI', 'Analog Devices', ARRAY['NDX','SPX']::text[]),
  ('ADM', 'Archer Daniels Midland', ARRAY['SPX']::text[]),
  ('ADP', 'Automatic Data Processing', ARRAY['NDX','SPX']::text[]),
  ('ADSK', 'Autodesk', ARRAY['NDX','SPX']::text[]),
  ('AEE', 'Ameren', ARRAY['SPX']::text[]),
  ('AEP', 'American Electric Power', ARRAY['NDX','SPX']::text[]),
  ('AES', 'AES Corporation', ARRAY['SPX']::text[]),
  ('AFL', 'Aflac', ARRAY['SPX']::text[]),
  ('AIG', 'American International Group', ARRAY['SPX']::text[]),
  ('AIZ', 'Assurant', ARRAY['SPX']::text[]),
  ('AJG', 'Arthur J. Gallagher & Co.', ARRAY['SPX']::text[]),
  ('AKAM', 'Akamai Technologies', ARRAY['SPX']::text[]),
  ('ALB', 'Albemarle Corporation', ARRAY['SPX']::text[]),
  ('ALGN', 'Align Technology', ARRAY['SPX']::text[]),
  ('ALL', 'Allstate', ARRAY['SPX']::text[]),
  ('ALLE', 'Allegion', ARRAY['SPX']::text[]),
  ('ALNY', 'Alnylam Pharmaceuticals', ARRAY['NDX']::text[]),
  ('AMAT', 'Applied Materials', ARRAY['NDX','SPX']::text[]),
  ('AMCR', 'Amcor', ARRAY['SPX']::text[]),
  ('AMD', 'Advanced Micro Devices', ARRAY['NDX','SPX']::text[]),
  ('AME', 'Ametek', ARRAY['SPX']::text[]),
  ('AMGN', 'Amgen', ARRAY['NDX','SPX']::text[]),
  ('AMP', 'Ameriprise Financial', ARRAY['SPX']::text[]),
  ('AMT', 'American Tower', ARRAY['SPX']::text[]),
  ('AMZN', 'Amazon', ARRAY['NDX','SPX']::text[]),
  ('ANET', 'Arista Networks', ARRAY['SPX']::text[]),
  ('AON', 'Aon plc', ARRAY['SPX']::text[]),
  ('AOS', 'A. O. Smith', ARRAY['SPX']::text[]),
  ('APA', 'APA Corporation', ARRAY['SPX']::text[]),
  ('APD', 'Air Products', ARRAY['SPX']::text[]),
  ('APH', 'Amphenol', ARRAY['SPX']::text[]),
  ('APO', 'Apollo Global Management', ARRAY['SPX']::text[]),
  ('APP', 'AppLovin', ARRAY['NDX','SPX']::text[]),
  ('APTV', 'Aptiv', ARRAY['SPX']::text[]),
  ('ARE', 'Alexandria Real Estate Equities', ARRAY['SPX']::text[]),
  ('ARES', 'Ares Management', ARRAY['SPX']::text[]),
  ('ARM', 'Arm Holdings', ARRAY['NDX']::text[]),
  ('ASML', 'ASML Holding', ARRAY['NDX']::text[]),
  ('ATO', 'Atmos Energy', ARRAY['SPX']::text[]),
  ('AVB', 'AvalonBay Communities', ARRAY['SPX']::text[]),
  ('AVGO', 'Broadcom', ARRAY['NDX','SPX']::text[]),
  ('AVY', 'Avery Dennison', ARRAY['SPX']::text[]),
  ('AWK', 'American Water Works', ARRAY['SPX']::text[]),
  ('AXON', 'Axon Enterprise', ARRAY['NDX','SPX']::text[]),
  ('AXP', 'American Express', ARRAY['SPX']::text[]),
  ('AZO', 'AutoZone', ARRAY['SPX']::text[]),
  ('BA', 'Boeing', ARRAY['SPX']::text[]),
  ('BAC', 'Bank of America', ARRAY['SPX']::text[]),
  ('BALL', 'Ball Corporation', ARRAY['SPX']::text[]),
  ('BAX', 'Baxter International', ARRAY['SPX']::text[]),
  ('BBY', 'Best Buy', ARRAY['SPX']::text[]),
  ('BDX', 'Becton Dickinson', ARRAY['SPX']::text[]),
  ('BEN', 'Franklin Resources', ARRAY['SPX']::text[]),
  ('BF.B', 'Brown–Forman', ARRAY['SPX']::text[]),
  ('BG', 'Bunge Global', ARRAY['SPX']::text[]),
  ('BIIB', 'Biogen', ARRAY['SPX']::text[]),
  ('BK', 'BNY Mellon', ARRAY['SPX']::text[]),
  ('BKNG', 'Booking Holdings', ARRAY['NDX','SPX']::text[]),
  ('BKR', 'Baker Hughes', ARRAY['NDX','SPX']::text[]),
  ('BLDR', 'Builders FirstSource', ARRAY['SPX']::text[]),
  ('BLK', 'BlackRock', ARRAY['SPX']::text[]),
  ('BMY', 'Bristol Myers Squibb', ARRAY['SPX']::text[]),
  ('BR', 'Broadridge Financial Solutions', ARRAY['SPX']::text[]),
  ('BRK.B', 'Berkshire Hathaway', ARRAY['SPX']::text[]),
  ('BRO', 'Brown & Brown', ARRAY['SPX']::text[]),
  ('BSX', 'Boston Scientific', ARRAY['SPX']::text[]),
  ('BX', 'Blackstone Inc.', ARRAY['SPX']::text[]),
  ('BXP', 'BXP, Inc.', ARRAY['SPX']::text[]),
  ('C', 'Citigroup', ARRAY['SPX']::text[]),
  ('CAG', 'Conagra Brands', ARRAY['SPX']::text[]),
  ('CAH', 'Cardinal Health', ARRAY['SPX']::text[]),
  ('CARR', 'Carrier Global', ARRAY['SPX']::text[]),
  ('CASY', 'Casey''s', ARRAY['SPX']::text[]),
  ('CAT', 'Caterpillar Inc.', ARRAY['SPX']::text[]),
  ('CB', 'Chubb Limited', ARRAY['SPX']::text[]),
  ('CBOE', 'Cboe Global Markets', ARRAY['SPX']::text[]),
  ('CBRE', 'CBRE Group', ARRAY['SPX']::text[]),
  ('CCEP', 'Coca-Cola Europacific Partners', ARRAY['NDX']::text[]),
  ('CCI', 'Crown Castle', ARRAY['SPX']::text[]),
  ('CCL', 'Carnival', ARRAY['SPX']::text[]),
  ('CDNS', 'Cadence Design Systems', ARRAY['NDX','SPX']::text[]),
  ('CDW', 'CDW Corporation', ARRAY['SPX']::text[]),
  ('CEG', 'Constellation Energy', ARRAY['NDX','SPX']::text[]),
  ('CF', 'CF Industries', ARRAY['SPX']::text[]),
  ('CFG', 'Citizens Financial Group', ARRAY['SPX']::text[]),
  ('CHD', 'Church & Dwight', ARRAY['SPX']::text[]),
  ('CHRW', 'C.H. Robinson', ARRAY['SPX']::text[]),
  ('CHTR', 'Charter Communications', ARRAY['NDX','SPX']::text[]),
  ('CI', 'Cigna', ARRAY['SPX']::text[]),
  ('CIEN', 'Ciena', ARRAY['SPX']::text[]),
  ('CINF', 'Cincinnati Financial', ARRAY['SPX']::text[]),
  ('CL', 'Colgate-Palmolive', ARRAY['SPX']::text[]),
  ('CLX', 'Clorox', ARRAY['SPX']::text[]),
  ('CMCSA', 'Comcast', ARRAY['NDX','SPX']::text[]),
  ('CME', 'CME Group', ARRAY['SPX']::text[]),
  ('CMG', 'Chipotle Mexican Grill', ARRAY['SPX']::text[]),
  ('CMI', 'Cummins', ARRAY['SPX']::text[]),
  ('CMS', 'CMS Energy', ARRAY['SPX']::text[]),
  ('CNC', 'Centene Corporation', ARRAY['SPX']::text[]),
  ('CNP', 'CenterPoint Energy', ARRAY['SPX']::text[]),
  ('COF', 'Capital One', ARRAY['SPX']::text[]),
  ('COHR', 'Coherent Corp.', ARRAY['SPX']::text[]),
  ('COIN', 'Coinbase', ARRAY['SPX']::text[]),
  ('COO', 'Cooper Companies (The)', ARRAY['SPX']::text[]),
  ('COP', 'ConocoPhillips', ARRAY['SPX']::text[]),
  ('COR', 'Cencora', ARRAY['SPX']::text[]),
  ('COST', 'Costco', ARRAY['NDX','SPX']::text[]),
  ('CPAY', 'Corpay', ARRAY['SPX']::text[]),
  ('CPB', 'Campbell''s Company (The)', ARRAY['SPX']::text[]),
  ('CPRT', 'Copart', ARRAY['NDX','SPX']::text[]),
  ('CPT', 'Camden Property Trust', ARRAY['SPX']::text[]),
  ('CRH', 'CRH plc', ARRAY['SPX']::text[]),
  ('CRL', 'Charles River Laboratories', ARRAY['SPX']::text[]),
  ('CRM', 'Salesforce', ARRAY['SPX']::text[]),
  ('CRWD', 'CrowdStrike', ARRAY['NDX','SPX']::text[]),
  ('CSCO', 'Cisco', ARRAY['NDX','SPX']::text[]),
  ('CSGP', 'CoStar Group', ARRAY['NDX','SPX']::text[]),
  ('CSX', 'CSX Corporation', ARRAY['NDX','SPX']::text[]),
  ('CTAS', 'Cintas', ARRAY['NDX','SPX']::text[]),
  ('CTRA', 'Coterra', ARRAY['SPX']::text[]),
  ('CTSH', 'Cognizant', ARRAY['NDX','SPX']::text[]),
  ('CTVA', 'Corteva', ARRAY['SPX']::text[]),
  ('CVNA', 'Carvana', ARRAY['SPX']::text[]),
  ('CVS', 'CVS Health', ARRAY['SPX']::text[]),
  ('CVX', 'Chevron Corporation', ARRAY['SPX']::text[]),
  ('D', 'Dominion Energy', ARRAY['SPX']::text[]),
  ('DAL', 'Delta Air Lines', ARRAY['SPX']::text[]),
  ('DASH', 'DoorDash', ARRAY['NDX','SPX']::text[]),
  ('DD', 'DuPont', ARRAY['SPX']::text[]),
  ('DDOG', 'Datadog', ARRAY['NDX','SPX']::text[]),
  ('DE', 'Deere & Company', ARRAY['SPX']::text[]),
  ('DECK', 'Deckers Brands', ARRAY['SPX']::text[]),
  ('DELL', 'Dell Technologies', ARRAY['SPX']::text[]),
  ('DG', 'Dollar General', ARRAY['SPX']::text[]),
  ('DGX', 'Quest Diagnostics', ARRAY['SPX']::text[]),
  ('DHI', 'D. R. Horton', ARRAY['SPX']::text[]),
  ('DHR', 'Danaher Corporation', ARRAY['SPX']::text[]),
  ('DIS', 'Walt Disney Company (The)', ARRAY['SPX']::text[]),
  ('DLR', 'Digital Realty', ARRAY['SPX']::text[]),
  ('DLTR', 'Dollar Tree', ARRAY['SPX']::text[]),
  ('DOC', 'Healthpeak Properties', ARRAY['SPX']::text[]),
  ('DOV', 'Dover Corporation', ARRAY['SPX']::text[]),
  ('DOW', 'Dow Inc.', ARRAY['SPX']::text[]),
  ('DPZ', 'Domino''s', ARRAY['SPX']::text[]),
  ('DRI', 'Darden Restaurants', ARRAY['SPX']::text[]),
  ('DTE', 'DTE Energy', ARRAY['SPX']::text[]),
  ('DUK', 'Duke Energy', ARRAY['SPX']::text[]),
  ('DVA', 'DaVita', ARRAY['SPX']::text[]),
  ('DVN', 'Devon Energy', ARRAY['SPX']::text[]),
  ('DXCM', 'Dexcom', ARRAY['NDX','SPX']::text[]),
  ('EA', 'Electronic Arts', ARRAY['NDX','SPX']::text[]),
  ('EBAY', 'eBay Inc.', ARRAY['SPX']::text[]),
  ('ECL', 'Ecolab', ARRAY['SPX']::text[]),
  ('ED', 'Consolidated Edison', ARRAY['SPX']::text[]),
  ('EFX', 'Equifax', ARRAY['SPX']::text[]),
  ('EG', 'Everest Group', ARRAY['SPX']::text[]),
  ('EIX', 'Edison International', ARRAY['SPX']::text[]),
  ('EL', 'Estée Lauder Companies (The)', ARRAY['SPX']::text[]),
  ('ELV', 'Elevance Health', ARRAY['SPX']::text[]),
  ('EME', 'Emcor', ARRAY['SPX']::text[]),
  ('EMR', 'Emerson Electric', ARRAY['SPX']::text[]),
  ('EOG', 'EOG Resources', ARRAY['SPX']::text[]),
  ('EPAM', 'EPAM Systems', ARRAY['SPX']::text[]),
  ('EQIX', 'Equinix', ARRAY['SPX']::text[]),
  ('EQR', 'Equity Residential', ARRAY['SPX']::text[]),
  ('EQT', 'EQT Corporation', ARRAY['SPX']::text[]),
  ('ERIE', 'Erie Indemnity', ARRAY['SPX']::text[]),
  ('ES', 'Eversource Energy', ARRAY['SPX']::text[]),
  ('ESS', 'Essex Property Trust', ARRAY['SPX']::text[]),
  ('ETN', 'Eaton Corporation', ARRAY['SPX']::text[]),
  ('ETR', 'Entergy', ARRAY['SPX']::text[]),
  ('EVRG', 'Evergy', ARRAY['SPX']::text[]),
  ('EW', 'Edwards Lifesciences', ARRAY['SPX']::text[]),
  ('EXC', 'Exelon', ARRAY['NDX','SPX']::text[]),
  ('EXE', 'Expand Energy', ARRAY['SPX']::text[]),
  ('EXPD', 'Expeditors International', ARRAY['SPX']::text[]),
  ('EXPE', 'Expedia Group', ARRAY['SPX']::text[]),
  ('EXR', 'Extra Space Storage', ARRAY['SPX']::text[]),
  ('F', 'Ford Motor Company', ARRAY['SPX']::text[]),
  ('FANG', 'Diamondback Energy', ARRAY['NDX','SPX']::text[]),
  ('FAST', 'Fastenal', ARRAY['NDX','SPX']::text[]),
  ('FCX', 'Freeport-McMoRan', ARRAY['SPX']::text[]),
  ('FDS', 'FactSet', ARRAY['SPX']::text[]),
  ('FDX', 'FedEx', ARRAY['SPX']::text[]),
  ('FE', 'FirstEnergy', ARRAY['SPX']::text[]),
  ('FER', 'Ferrovial', ARRAY['NDX']::text[]),
  ('FFIV', 'F5, Inc.', ARRAY['SPX']::text[]),
  ('FICO', 'Fair Isaac', ARRAY['SPX']::text[]),
  ('FIS', 'Fidelity National Information Services', ARRAY['SPX']::text[]),
  ('FISV', 'Fiserv', ARRAY['SPX']::text[]),
  ('FITB', 'Fifth Third Bancorp', ARRAY['SPX']::text[]),
  ('FIX', 'Comfort Systems USA', ARRAY['SPX']::text[]),
  ('FOX', 'Fox Corporation (Class B)', ARRAY['SPX']::text[]),
  ('FOXA', 'Fox Corporation (Class A)', ARRAY['SPX']::text[]),
  ('FRT', 'Federal Realty Investment Trust', ARRAY['SPX']::text[]),
  ('FSLR', 'First Solar', ARRAY['SPX']::text[]),
  ('FTNT', 'Fortinet', ARRAY['NDX','SPX']::text[]),
  ('FTV', 'Fortive', ARRAY['SPX']::text[]),
  ('GD', 'General Dynamics', ARRAY['SPX']::text[]),
  ('GDDY', 'GoDaddy', ARRAY['SPX']::text[]),
  ('GE', 'GE Aerospace', ARRAY['SPX']::text[]),
  ('GEHC', 'GE HealthCare', ARRAY['NDX','SPX']::text[]),
  ('GEN', 'Gen Digital', ARRAY['SPX']::text[]),
  ('GEV', 'GE Vernova', ARRAY['SPX']::text[]),
  ('GILD', 'Gilead Sciences', ARRAY['NDX','SPX']::text[]),
  ('GIS', 'General Mills', ARRAY['SPX']::text[]),
  ('GL', 'Globe Life', ARRAY['SPX']::text[]),
  ('GLW', 'Corning Inc.', ARRAY['SPX']::text[]),
  ('GM', 'General Motors', ARRAY['SPX']::text[]),
  ('GNRC', 'Generac', ARRAY['SPX']::text[]),
  ('GOOG', 'Alphabet Inc. (Class C)', ARRAY['NDX','SPX']::text[]),
  ('GOOGL', 'Alphabet Inc. (Class A)', ARRAY['NDX','SPX']::text[]),
  ('GPC', 'Genuine Parts Company', ARRAY['SPX']::text[]),
  ('GPN', 'Global Payments', ARRAY['SPX']::text[]),
  ('GRMN', 'Garmin', ARRAY['SPX']::text[]),
  ('GS', 'Goldman Sachs', ARRAY['SPX']::text[]),
  ('GWW', 'W. W. Grainger', ARRAY['SPX']::text[]),
  ('HAL', 'Halliburton', ARRAY['SPX']::text[]),
  ('HAS', 'Hasbro', ARRAY['SPX']::text[]),
  ('HBAN', 'Huntington Bancshares', ARRAY['SPX']::text[]),
  ('HCA', 'HCA Healthcare', ARRAY['SPX']::text[]),
  ('HD', 'Home Depot (The)', ARRAY['SPX']::text[]),
  ('HIG', 'Hartford (The)', ARRAY['SPX']::text[]),
  ('HII', 'Huntington Ingalls Industries', ARRAY['SPX']::text[]),
  ('HLT', 'Hilton Worldwide', ARRAY['SPX']::text[]),
  ('HON', 'Honeywell', ARRAY['NDX','SPX']::text[]),
  ('HOOD', 'Robinhood Markets', ARRAY['SPX']::text[]),
  ('HPE', 'Hewlett Packard Enterprise', ARRAY['SPX']::text[]),
  ('HPQ', 'HP Inc.', ARRAY['SPX']::text[]),
  ('HRL', 'Hormel Foods', ARRAY['SPX']::text[]),
  ('HSIC', 'Henry Schein', ARRAY['SPX']::text[]),
  ('HST', 'Host Hotels & Resorts', ARRAY['SPX']::text[]),
  ('HSY', 'Hershey Company (The)', ARRAY['SPX']::text[]),
  ('HUBB', 'Hubbell Incorporated', ARRAY['SPX']::text[]),
  ('HUM', 'Humana', ARRAY['SPX']::text[]),
  ('HWM', 'Howmet Aerospace', ARRAY['SPX']::text[]),
  ('IBKR', 'Interactive Brokers', ARRAY['SPX']::text[]),
  ('IBM', 'IBM', ARRAY['SPX']::text[]),
  ('ICE', 'Intercontinental Exchange', ARRAY['SPX']::text[]),
  ('IDXX', 'Idexx Laboratories', ARRAY['NDX','SPX']::text[]),
  ('IEX', 'IDEX Corporation', ARRAY['SPX']::text[]),
  ('IFF', 'International Flavors & Fragrances', ARRAY['SPX']::text[]),
  ('INCY', 'Incyte', ARRAY['SPX']::text[]),
  ('INSM', 'Insmed Incorporated', ARRAY['NDX']::text[]),
  ('INTC', 'Intel', ARRAY['NDX','SPX']::text[]),
  ('INTU', 'Intuit', ARRAY['NDX','SPX']::text[]),
  ('INVH', 'Invitation Homes', ARRAY['SPX']::text[]),
  ('IP', 'International Paper', ARRAY['SPX']::text[]),
  ('IQV', 'IQVIA', ARRAY['SPX']::text[]),
  ('IR', 'Ingersoll Rand', ARRAY['SPX']::text[]),
  ('IRM', 'Iron Mountain', ARRAY['SPX']::text[]),
  ('ISRG', 'Intuitive Surgical', ARRAY['NDX','SPX']::text[]),
  ('IT', 'Gartner', ARRAY['SPX']::text[]),
  ('ITW', 'Illinois Tool Works', ARRAY['SPX']::text[]),
  ('IVZ', 'Invesco', ARRAY['SPX']::text[]),
  ('J', 'Jacobs Solutions', ARRAY['SPX']::text[]),
  ('JBHT', 'J.B. Hunt', ARRAY['SPX']::text[]),
  ('JBL', 'Jabil', ARRAY['SPX']::text[]),
  ('JCI', 'Johnson Controls', ARRAY['SPX']::text[]),
  ('JKHY', 'Jack Henry & Associates', ARRAY['SPX']::text[]),
  ('JNJ', 'Johnson & Johnson', ARRAY['SPX']::text[]),
  ('JPM', 'JPMorgan Chase', ARRAY['SPX']::text[]),
  ('KDP', 'Keurig Dr Pepper', ARRAY['NDX','SPX']::text[]),
  ('KEY', 'KeyCorp', ARRAY['SPX']::text[]),
  ('KEYS', 'Keysight Technologies', ARRAY['SPX']::text[]),
  ('KHC', 'Kraft Heinz', ARRAY['NDX','SPX']::text[]),
  ('KIM', 'Kimco Realty', ARRAY['SPX']::text[]),
  ('KKR', 'KKR & Co.', ARRAY['SPX']::text[]),
  ('KLAC', 'KLA Corporation', ARRAY['NDX','SPX']::text[]),
  ('KMB', 'Kimberly-Clark', ARRAY['SPX']::text[]),
  ('KMI', 'Kinder Morgan', ARRAY['SPX']::text[]),
  ('KO', 'Coca-Cola Company (The)', ARRAY['SPX']::text[]),
  ('KR', 'Kroger', ARRAY['SPX']::text[]),
  ('KVUE', 'Kenvue', ARRAY['SPX']::text[]),
  ('L', 'Loews Corporation', ARRAY['SPX']::text[]),
  ('LDOS', 'Leidos', ARRAY['SPX']::text[]),
  ('LEN', 'Lennar', ARRAY['SPX']::text[]),
  ('LH', 'Labcorp', ARRAY['SPX']::text[]),
  ('LHX', 'L3Harris', ARRAY['SPX']::text[]),
  ('LII', 'Lennox International', ARRAY['SPX']::text[]),
  ('LIN', 'Linde plc', ARRAY['NDX','SPX']::text[]),
  ('LITE', 'Lumentum', ARRAY['SPX']::text[]),
  ('LLY', 'Lilly (Eli)', ARRAY['SPX']::text[]),
  ('LMT', 'Lockheed Martin', ARRAY['SPX']::text[]),
  ('LNT', 'Alliant Energy', ARRAY['SPX']::text[]),
  ('LOW', 'Lowe''s', ARRAY['SPX']::text[]),
  ('LRCX', 'Lam Research', ARRAY['NDX','SPX']::text[]),
  ('LULU', 'Lululemon Athletica', ARRAY['SPX']::text[]),
  ('LUV', 'Southwest Airlines', ARRAY['SPX']::text[]),
  ('LVS', 'Las Vegas Sands', ARRAY['SPX']::text[]),
  ('LYB', 'LyondellBasell', ARRAY['SPX']::text[]),
  ('LYV', 'Live Nation Entertainment', ARRAY['SPX']::text[]),
  ('MA', 'Mastercard', ARRAY['SPX']::text[]),
  ('MAA', 'Mid-America Apartment Communities', ARRAY['SPX']::text[]),
  ('MAR', 'Marriott International', ARRAY['NDX','SPX']::text[]),
  ('MAS', 'Masco', ARRAY['SPX']::text[]),
  ('MCD', 'McDonald''s', ARRAY['SPX']::text[]),
  ('MCHP', 'Microchip Technology', ARRAY['NDX','SPX']::text[]),
  ('MCK', 'McKesson Corporation', ARRAY['SPX']::text[]),
  ('MCO', 'Moody''s Corporation', ARRAY['SPX']::text[]),
  ('MDLZ', 'Mondelez International', ARRAY['NDX','SPX']::text[]),
  ('MDT', 'Medtronic', ARRAY['SPX']::text[]),
  ('MELI', 'Mercado Libre', ARRAY['NDX']::text[]),
  ('MET', 'MetLife', ARRAY['SPX']::text[]),
  ('META', 'Meta Platforms', ARRAY['NDX','SPX']::text[]),
  ('MGM', 'MGM Resorts', ARRAY['SPX']::text[]),
  ('MKC', 'McCormick & Company', ARRAY['SPX']::text[]),
  ('MLM', 'Martin Marietta Materials', ARRAY['SPX']::text[]),
  ('MMM', '3M', ARRAY['SPX']::text[]),
  ('MNST', 'Monster Beverage', ARRAY['NDX','SPX']::text[]),
  ('MO', 'Altria', ARRAY['SPX']::text[]),
  ('MOS', 'Mosaic Company (The)', ARRAY['SPX']::text[]),
  ('MPC', 'Marathon Petroleum', ARRAY['SPX']::text[]),
  ('MPWR', 'Monolithic Power Systems', ARRAY['NDX','SPX']::text[]),
  ('MRK', 'Merck & Co.', ARRAY['SPX']::text[]),
  ('MRNA', 'Moderna', ARRAY['SPX']::text[]),
  ('MRSH', 'Marsh McLennan', ARRAY['SPX']::text[]),
  ('MRVL', 'Marvell Technology', ARRAY['NDX']::text[]),
  ('MS', 'Morgan Stanley', ARRAY['SPX']::text[]),
  ('MSCI', 'MSCI Inc.', ARRAY['SPX']::text[]),
  ('MSFT', 'Microsoft', ARRAY['NDX','SPX']::text[]),
  ('MSI', 'Motorola Solutions', ARRAY['SPX']::text[]),
  ('MSTR', 'MicroStrategy', ARRAY['NDX']::text[]),
  ('MTB', 'M&T Bank', ARRAY['SPX']::text[]),
  ('MTD', 'Mettler Toledo', ARRAY['SPX']::text[]),
  ('MU', 'Micron Technology', ARRAY['NDX','SPX']::text[]),
  ('NCLH', 'Norwegian Cruise Line Holdings', ARRAY['SPX']::text[]),
  ('NDAQ', 'Nasdaq, Inc.', ARRAY['SPX']::text[]),
  ('NDSN', 'Nordson Corporation', ARRAY['SPX']::text[]),
  ('NEE', 'NextEra Energy', ARRAY['SPX']::text[]),
  ('NEM', 'Newmont', ARRAY['SPX']::text[]),
  ('NFLX', 'Netflix', ARRAY['NDX','SPX']::text[]),
  ('NI', 'NiSource', ARRAY['SPX']::text[]),
  ('NKE', 'Nike, Inc.', ARRAY['SPX']::text[]),
  ('NOC', 'Northrop Grumman', ARRAY['SPX']::text[]),
  ('NOW', 'ServiceNow', ARRAY['SPX']::text[]),
  ('NRG', 'NRG Energy', ARRAY['SPX']::text[]),
  ('NSC', 'Norfolk Southern', ARRAY['SPX']::text[]),
  ('NTAP', 'NetApp', ARRAY['SPX']::text[]),
  ('NTRS', 'Northern Trust', ARRAY['SPX']::text[]),
  ('NUE', 'Nucor', ARRAY['SPX']::text[]),
  ('NVDA', 'Nvidia', ARRAY['NDX','SPX']::text[]),
  ('NVR', 'NVR, Inc.', ARRAY['SPX']::text[]),
  ('NWS', 'News Corp (Class B)', ARRAY['SPX']::text[]),
  ('NWSA', 'News Corp (Class A)', ARRAY['SPX']::text[]),
  ('NXPI', 'NXP Semiconductors', ARRAY['NDX','SPX']::text[]),
  ('O', 'Realty Income', ARRAY['SPX']::text[]),
  ('ODFL', 'Old Dominion', ARRAY['NDX','SPX']::text[]),
  ('OKE', 'Oneok', ARRAY['SPX']::text[]),
  ('OMC', 'Omnicom Group', ARRAY['SPX']::text[]),
  ('ON', 'ON Semiconductor', ARRAY['SPX']::text[]),
  ('ORCL', 'Oracle Corporation', ARRAY['SPX']::text[]),
  ('ORLY', 'O’Reilly Automotive', ARRAY['NDX','SPX']::text[]),
  ('OTIS', 'Otis Worldwide', ARRAY['SPX']::text[]),
  ('OXY', 'Occidental Petroleum', ARRAY['SPX']::text[]),
  ('PANW', 'Palo Alto Networks', ARRAY['NDX','SPX']::text[]),
  ('PAYX', 'Paychex', ARRAY['NDX','SPX']::text[]),
  ('PCAR', 'Paccar', ARRAY['NDX','SPX']::text[]),
  ('PCG', 'PG&E Corporation', ARRAY['SPX']::text[]),
  ('PDD', 'PDD Holdings', ARRAY['NDX']::text[]),
  ('PEG', 'Public Service Enterprise Group', ARRAY['SPX']::text[]),
  ('PEP', 'PepsiCo', ARRAY['NDX','SPX']::text[]),
  ('PFE', 'Pfizer', ARRAY['SPX']::text[]),
  ('PFG', 'Principal Financial Group', ARRAY['SPX']::text[]),
  ('PG', 'Procter & Gamble', ARRAY['SPX']::text[]),
  ('PGR', 'Progressive Corporation', ARRAY['SPX']::text[]),
  ('PH', 'Parker Hannifin', ARRAY['SPX']::text[]),
  ('PHM', 'PulteGroup', ARRAY['SPX']::text[]),
  ('PKG', 'Packaging Corporation of America', ARRAY['SPX']::text[]),
  ('PLD', 'Prologis', ARRAY['SPX']::text[]),
  ('PLTR', 'Palantir Technologies', ARRAY['NDX','SPX']::text[]),
  ('PM', 'Philip Morris International', ARRAY['SPX']::text[]),
  ('PNC', 'PNC Financial Services', ARRAY['SPX']::text[]),
  ('PNR', 'Pentair', ARRAY['SPX']::text[]),
  ('PNW', 'Pinnacle West Capital', ARRAY['SPX']::text[]),
  ('PODD', 'Insulet Corporation', ARRAY['SPX']::text[]),
  ('POOL', 'Pool Corporation', ARRAY['SPX']::text[]),
  ('PPG', 'PPG Industries', ARRAY['SPX']::text[]),
  ('PPL', 'PPL Corporation', ARRAY['SPX']::text[]),
  ('PRU', 'Prudential Financial', ARRAY['SPX']::text[]),
  ('PSA', 'Public Storage', ARRAY['SPX']::text[]),
  ('PSKY', 'Paramount Skydance Corporation', ARRAY['SPX']::text[]),
  ('PSX', 'Phillips 66', ARRAY['SPX']::text[]),
  ('PTC', 'PTC Inc.', ARRAY['SPX']::text[]),
  ('PWR', 'Quanta Services', ARRAY['SPX']::text[]),
  ('PYPL', 'PayPal', ARRAY['NDX','SPX']::text[]),
  ('Q', 'Qnity Electronics', ARRAY['SPX']::text[]),
  ('QCOM', 'Qualcomm', ARRAY['NDX','SPX']::text[]),
  ('RCL', 'Royal Caribbean Group', ARRAY['SPX']::text[]),
  ('REG', 'Regency Centers', ARRAY['SPX']::text[]),
  ('REGN', 'Regeneron Pharmaceuticals', ARRAY['NDX','SPX']::text[]),
  ('RF', 'Regions Financial Corporation', ARRAY['SPX']::text[]),
  ('RJF', 'Raymond James Financial', ARRAY['SPX']::text[]),
  ('RL', 'Ralph Lauren Corporation', ARRAY['SPX']::text[]),
  ('RMD', 'ResMed', ARRAY['SPX']::text[]),
  ('ROK', 'Rockwell Automation', ARRAY['SPX']::text[]),
  ('ROL', 'Rollins, Inc.', ARRAY['SPX']::text[]),
  ('ROP', 'Roper Technologies', ARRAY['NDX','SPX']::text[]),
  ('ROST', 'Ross Stores', ARRAY['NDX','SPX']::text[]),
  ('RSG', 'Republic Services', ARRAY['SPX']::text[]),
  ('RTX', 'RTX Corporation', ARRAY['SPX']::text[]),
  ('RVTY', 'Revvity', ARRAY['SPX']::text[]),
  ('SATS', 'EchoStar', ARRAY['SPX']::text[]),
  ('SBAC', 'SBA Communications', ARRAY['SPX']::text[]),
  ('SBUX', 'Starbucks', ARRAY['NDX','SPX']::text[]),
  ('SCHW', 'Charles Schwab Corporation', ARRAY['SPX']::text[]),
  ('SHOP', 'Shopify', ARRAY['NDX']::text[]),
  ('SHW', 'Sherwin-Williams', ARRAY['SPX']::text[]),
  ('SJM', 'J.M. Smucker Company (The)', ARRAY['SPX']::text[]),
  ('SLB', 'Schlumberger', ARRAY['SPX']::text[]),
  ('SMCI', 'Supermicro', ARRAY['SPX']::text[]),
  ('SNA', 'Snap-on', ARRAY['SPX']::text[]),
  ('SNDK', 'Sandisk', ARRAY['NDX','SPX']::text[]),
  ('SNPS', 'Synopsys', ARRAY['NDX','SPX']::text[]),
  ('SO', 'Southern Company', ARRAY['SPX']::text[]),
  ('SOLV', 'Solventum', ARRAY['SPX']::text[]),
  ('SPG', 'Simon Property Group', ARRAY['SPX']::text[]),
  ('SPGI', 'S&P Global', ARRAY['SPX']::text[]),
  ('SRE', 'Sempra', ARRAY['SPX']::text[]),
  ('STE', 'Steris', ARRAY['SPX']::text[]),
  ('STLD', 'Steel Dynamics', ARRAY['SPX']::text[]),
  ('STT', 'State Street Corporation', ARRAY['SPX']::text[]),
  ('STX', 'Seagate Technology', ARRAY['NDX','SPX']::text[]),
  ('STZ', 'Constellation Brands', ARRAY['SPX']::text[]),
  ('SW', 'Smurfit Westrock', ARRAY['SPX']::text[]),
  ('SWK', 'Stanley Black & Decker', ARRAY['SPX']::text[]),
  ('SWKS', 'Skyworks Solutions', ARRAY['SPX']::text[]),
  ('SYF', 'Synchrony Financial', ARRAY['SPX']::text[]),
  ('SYK', 'Stryker Corporation', ARRAY['SPX']::text[]),
  ('SYY', 'Sysco', ARRAY['SPX']::text[]),
  ('T', 'AT&T', ARRAY['SPX']::text[]),
  ('TAP', 'Molson Coors Beverage Company', ARRAY['SPX']::text[]),
  ('TDG', 'TransDigm Group', ARRAY['SPX']::text[]),
  ('TDY', 'Teledyne Technologies', ARRAY['SPX']::text[]),
  ('TECH', 'Bio-Techne', ARRAY['SPX']::text[]),
  ('TEL', 'TE Connectivity', ARRAY['SPX']::text[]),
  ('TER', 'Teradyne', ARRAY['SPX']::text[]),
  ('TFC', 'Truist Financial', ARRAY['SPX']::text[]),
  ('TGT', 'Target Corporation', ARRAY['SPX']::text[]),
  ('TICKER', 'Company', ARRAY['NDX']::text[]),
  ('TJX', 'TJX Companies', ARRAY['SPX']::text[]),
  ('TKO', 'TKO Group Holdings', ARRAY['SPX']::text[]),
  ('TMO', 'Thermo Fisher Scientific', ARRAY['SPX']::text[]),
  ('TMUS', 'T-Mobile US', ARRAY['NDX','SPX']::text[]),
  ('TPL', 'Texas Pacific Land Corporation', ARRAY['SPX']::text[]),
  ('TPR', 'Tapestry, Inc.', ARRAY['SPX']::text[]),
  ('TRGP', 'Targa Resources', ARRAY['SPX']::text[]),
  ('TRI', 'Thomson Reuters', ARRAY['NDX']::text[]),
  ('TRMB', 'Trimble Inc.', ARRAY['SPX']::text[]),
  ('TROW', 'T. Rowe Price', ARRAY['SPX']::text[]),
  ('TRV', 'Travelers Companies (The)', ARRAY['SPX']::text[]),
  ('TSCO', 'Tractor Supply', ARRAY['SPX']::text[]),
  ('TSLA', 'Tesla, Inc.', ARRAY['NDX','SPX']::text[]),
  ('TSN', 'Tyson Foods', ARRAY['SPX']::text[]),
  ('TT', 'Trane Technologies', ARRAY['SPX']::text[]),
  ('TTD', 'Trade Desk (The)', ARRAY['SPX']::text[]),
  ('TTWO', 'Take-Two Interactive', ARRAY['NDX','SPX']::text[]),
  ('TXN', 'Texas Instruments', ARRAY['NDX','SPX']::text[]),
  ('TXT', 'Textron', ARRAY['SPX']::text[]),
  ('TYL', 'Tyler Technologies', ARRAY['SPX']::text[]),
  ('UAL', 'United Airlines Holdings', ARRAY['SPX']::text[]),
  ('UBER', 'Uber', ARRAY['SPX']::text[]),
  ('UDR', 'UDR, Inc.', ARRAY['SPX']::text[]),
  ('UHS', 'Universal Health Services', ARRAY['SPX']::text[]),
  ('ULTA', 'Ulta Beauty', ARRAY['SPX']::text[]),
  ('UNH', 'UnitedHealth Group', ARRAY['SPX']::text[]),
  ('UNP', 'Union Pacific Corporation', ARRAY['SPX']::text[]),
  ('UPS', 'United Parcel Service', ARRAY['SPX']::text[]),
  ('URI', 'United Rentals', ARRAY['SPX']::text[]),
  ('USB', 'U.S. Bancorp', ARRAY['SPX']::text[]),
  ('V', 'Visa Inc.', ARRAY['SPX']::text[]),
  ('VICI', 'Vici Properties', ARRAY['SPX']::text[]),
  ('VLO', 'Valero Energy', ARRAY['SPX']::text[]),
  ('VLTO', 'Veralto', ARRAY['SPX']::text[]),
  ('VMC', 'Vulcan Materials Company', ARRAY['SPX']::text[]),
  ('VRSK', 'Verisk Analytics', ARRAY['NDX','SPX']::text[]),
  ('VRSN', 'Verisign', ARRAY['SPX']::text[]),
  ('VRT', 'Vertiv', ARRAY['SPX']::text[]),
  ('VRTX', 'Vertex Pharmaceuticals', ARRAY['NDX','SPX']::text[]),
  ('VST', 'Vistra Corp.', ARRAY['SPX']::text[]),
  ('VTR', 'Ventas', ARRAY['SPX']::text[]),
  ('VTRS', 'Viatris', ARRAY['SPX']::text[]),
  ('VZ', 'Verizon', ARRAY['SPX']::text[]),
  ('WAB', 'Wabtec', ARRAY['SPX']::text[]),
  ('WAT', 'Waters Corporation', ARRAY['SPX']::text[]),
  ('WBD', 'Warner Bros. Discovery', ARRAY['NDX','SPX']::text[]),
  ('WDAY', 'Workday, Inc.', ARRAY['NDX','SPX']::text[]),
  ('WDC', 'Western Digital', ARRAY['NDX','SPX']::text[]),
  ('WEC', 'WEC Energy Group', ARRAY['SPX']::text[]),
  ('WELL', 'Welltower', ARRAY['SPX']::text[]),
  ('WFC', 'Wells Fargo', ARRAY['SPX']::text[]),
  ('WM', 'Waste Management', ARRAY['SPX']::text[]),
  ('WMB', 'Williams Companies', ARRAY['SPX']::text[]),
  ('WMT', 'Walmart', ARRAY['NDX','SPX']::text[]),
  ('WRB', 'W. R. Berkley Corporation', ARRAY['SPX']::text[]),
  ('WSM', 'Williams-Sonoma, Inc.', ARRAY['SPX']::text[]),
  ('WST', 'West Pharmaceutical Services', ARRAY['SPX']::text[]),
  ('WTW', 'Willis Towers Watson', ARRAY['SPX']::text[]),
  ('WY', 'Weyerhaeuser', ARRAY['SPX']::text[]),
  ('WYNN', 'Wynn Resorts', ARRAY['SPX']::text[]),
  ('XEL', 'Xcel Energy', ARRAY['NDX','SPX']::text[]),
  ('XOM', 'ExxonMobil', ARRAY['SPX']::text[]),
  ('XYL', 'Xylem Inc.', ARRAY['SPX']::text[]),
  ('XYZ', 'Block, Inc.', ARRAY['SPX']::text[]),
  ('YUM', 'Yum! Brands', ARRAY['SPX']::text[]),
  ('ZBH', 'Zimmer Biomet', ARRAY['SPX']::text[]),
  ('ZBRA', 'Zebra Technologies', ARRAY['SPX']::text[]),
  ('ZS', 'Zscaler', ARRAY['NDX']::text[]),
  ('ZTS', 'Zoetis', ARRAY['SPX']::text[]);
